@startuml
'Fonctionnalite 14, 15 et 16 : Camera

skinparam monochrome true

start

:Ouvrir camera?;
:Camera.open();

fork
    while (camera active = 0) is (false)
        :image=camera.grab();
        :I=Img.ToJpg(image);
        :ComMonitor.Write(Message(I));
    endwhile (true)

fork again
'Attendre le signal de fermeture de la camera
    :Fermer camera?; 
    :Camera.close();
    :Stopper envoi;

end fork
stop
@enduml
