@startuml
'Fonctionnalite 8 et 9 : 

skinparam monochrome true

start
:robotStarted?;

repeat
repeat
:MsgtoRobot?msg;

if (msg==Nak||error||timeout) then (no)
  :compteur=0;
  else (yes)
  :compteur=compteur+1;
endif

repeat while (compteur <= 3)
-> no; 
:ComMonitor.Write(Lost_DMB);
:ComRobot.Close();
:robotStarted=0;
:OuvrirComRobot!;



repeat while (robotStarted) is (yes)
stop
@enduml
