@startuml
'Fonctionnalite 8 et 9 : 

skinparam monochrome true

start
repeat
:MsgtoRobot?msg;

if (msg==Nak||error||timeout) then (yes)
  :compteur=0;
  else (no)
  :compteur=compteur+1;
endif

repeat while (compteur <= 3)
-> no; 
:ComMonitor.Write(Lost_DMB);
:ComRobot.Close();
:OuvrirComRobot!;




stop
@enduml
