@startuml
skinparam monochrome true
start
:serverOk?;
while()
  :msgRcv = monitor.Read();
  if (msgRcv.CompareID(MESSAGE_MONITOR_LOST)) then (true)
  :lostComRS!;
   stop
  else (false)
   if (msgRcv.CompareID(MESSAGE_ROBOT_COM_OPEN)) then (true)
    :openComRobot!;
   else (false)
    if (msgRcv.CompareID(MESSAGE_ROBOT_START_WITHOUT_WD))
     :withWd=0; 
     :startRobot!;
    else (false)
     if (msgRcv.CompareID(MESSAGE_ROBOT_START_WITH_WD))
      :withWd=1;
      :startRobot!;
     else
      if (msgRcv.CompareID(MESSAGE_CAM_OPEN))
      :openCam=1;
      :createTask(th_vision);
      :runTask(th_vision);
      :ouvrirCamera!;
      else 
       if (msgRcv.CompareID(MESSAGE_CAM_CLOSE))
        :openCam=0;
        :fermerCamera!;
       else 
        if (msgRcv.CompareID(MESSAGE_CAM_ASK_ARENA))
         :findArena=1;
         :RechercherArena!;
        else 
         if (msgRcv.CompareID(MESSAGE_CAM_ARENA_CONFIRM))
          :arenaOK=1;
          :arenaOk!; 
         else 
          if (msgRcv.CompareID(MESSAGE_CAM_ARENA_INFIRM))
           :arenaOK=0;
           :arenaOk!; 
          else
           if (msgRcv.CompareID(MESSAGE_CAM_POSITION_COMPUTE_START))
            :findPosition=1; 
           else 
            if (msgRcv.CompareID(MESSAGE_CAM_POSITION_COMPUTE_STOP))
             :findPosition=0; 
           else 

      if (msgRcv.CompareID(MESSAGE_ROBOT_GO_FORWARD
       || msgRcv.CompareID(MESSAGE_ROBOT_GO_BACKWARD
       || msgRcv.CompareID(MESSAGE_ROBOT_GO_LEFT
       || msgRcv.CompareID(MESSAGE_ROBOT_GO_RIGHT
       || msgRcv.CompareID(MESSAGE_ROBOT_STOP)) then (true)
       :move = msg.GetId();
             endif
            endif
           endif
          endif 
         endif
        endif
       endif
      endif
     endif    
    endif
   endif
  endif
endwhile
stop
@enduml
